#DBConfig
POSTGRES_ADDRESS = ''  ## INSERT YOUR DB ADDRESS IF IT'S NOT ON PANOPLY
POSTGRES_PORT = ''
POSTGRES_DBNAME = ''

#UserDB
POSTGRES_USERNAME = ''  ## CHANGE THIS TO YOUR PANOPLY/POSTGRES USERNAME
POSTGRES_PASSWORD = ''  ## CHANGE THIS TO YOUR PANOPLY/POSTGRES PASSWORD POSTGRES_DBNAME = 'database' ## CHANGE THIS TO YOUR DATABASE NAME

#Flask Defaul
PORT = 5000
HOST = 'localhost'